---
- hosts: localhost
  gather_facts: yes
  tasks:
    - block:
      - name: installing git package
        yum:
          name: git
          state: present
      - name: installing httpd
        yum:
          name: httpd
          state: present
      when: ansible_os_family == "RedHat"
      become: yes
        
    - block:
      - name: installing git package
        apt:
          name: git
          state: present
      - name: installing apache2
        apt:
          name: apache2
          state: present
      when: ansible_os_family == "Debian"
      become: yes

# block module is used when we have similar group of tasks. Here when is used for both git and httpd. so at a time we are using when and # become and it should be under "block".
# gather facts sholud be yes for become and debug module
