---
- hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: creating s3 bucker
      s3_bucket:
        name: jenkins-ansible-s3-buckettt
        state: present
        versioning: true
        region: ap-south-1
      register: s3_url
