---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: creating ec2 instance
      ec2:
        region: ap-south-1
        image: ami-06e6b44dd2af20ed0
        instance_type: t2.micro
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "ansible"
